name: Build APK

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: List files (Debug)
        run: ls -R

      - name: Clone Flutter SDK
        run: git clone --depth 1 --branch stable https://github.com/flutter/flutter.git ${{ github.workspace }}/flutter-sdk

      - name: Add Flutter to PATH
        run: echo "${{ github.workspace }}/flutter-sdk/bin" >> $GITHUB_PATH

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses
        run: yes | flutter doctor --android-licenses || true

      - name: Get dependencies (Common)
        run: flutter pub get
        working-directory: common

      - name: Get dependencies (App)
        run: flutter pub get
        working-directory: app

      - name: Build release APK
        run: flutter build apk --release
        working-directory: app

      - name: Upload release APK artifact
        uses: actions/upload-artifact@v7
        with:
          name: LocalSend-Root-release-APK
          path: app/build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
